defmodule ClinicDemoWeb.PageController do
  use ClinicDemoWeb, :controller

  alias ClinicDemo.Scheduling.VisitMachine
  alias ClinicDemo.Visits.Instance

  def home(conn, _params) do
    render(conn, :home)
  end

  def operator(conn, _params) do
    render(conn, :operator,
      recent_instances: recent_instances(),
      visit_machine_chart: VisitMachine.chart(),
      active_bundle: active_guard_bundle(),
      # The dev-only spec pages (storybook, surface gallery) link from the
      # hub's Infrastructure section only where their routes exist.
      dev_routes: Application.get_env(:clinic_demo, :dev_routes, false)
    )
  end

  # The surface gallery (dev-only route): every declared surface framed
  # in sequence — the spec page the storybook cannot be (see
  # PageHTML.Gallery's moduledoc). The list is the router's surface set,
  # restated here with labels; presence-style headers carry the route and
  # the surface_id so the page doubles as an inventory.
  def gallery(conn, _params) do
    surfaces = [
      {"Board", "/", "clinic_board"},
      {"Day", "/day", "clinic_day"},
      {"Flight", "/flight", "clinic_flight"},
      {"Intake", "/intake", "clinic_intake"},
      {"Schedule", "/schedule", "clinic_schedule"},
      {"Worklist", "/worklist", "clinic_worklist"},
      {"Visits", "/visits", "clinic_visits"},
      {"Patients", "/patients", "clinic_patients"},
      {"Clinicians", "/clinicians", "clinic_clinicians"},
      {"Processes", "/processes", "clinic_process_definitions"},
      {"Decisions", "/decisions", "clinic_decision_definitions"},
      {"Evidence", "/evaluations", "clinic_evaluations"},
      {"Emergency board", "/emergencies", "clinic_emergency_board"},
      {"Audit events", "/events", "clinic_events"},
      {"Canvas", "/canvas", "clinic_canvas"},
      {"Agent", "/agent", "clinic_agent"}
    ]

    render(conn, :gallery, surfaces: surfaces)
  end

  # The capstone slideshow: a static page (priv/static/deck/index.html,
  # generated by scripts/build_deck_html.mjs and committed). Plug.Static
  # already serves the deck's own files (/deck/deck.js, /deck/shots/*,
  # /deck/capstone-deck.pptx); this action is only the directory index,
  # because Plug.Static serves files, not indexes.
  def deck(conn, _params) do
    conn
    |> put_resp_content_type("text/html")
    |> send_file(200, Application.app_dir(:clinic_demo, "priv/static/deck/index.html"))
  end

  # The compliance bundle currently in force, for the hub's Audit section.
  # Nil when nothing is active (a fresh database before the seeds run).
  defp active_guard_bundle do
    case AshCompliance.Domain.active_policy_bundle(
           ClinicDemo.Compliance.organization_id(),
           authorize?: false
         ) do
      {:ok, %AshCompliance.Resources.PolicyBundle{} = bundle} -> bundle
      _ -> nil
    end
  end

  # The latest visit instances for the hub's "Recent visit processes" list.
  # The Visits surface cannot link a row out to the instance viewer (the
  # a2ui surface DSL has no external row links), so the hub carries the
  # cross-link instead. Guarded so a fresh database without the engine's
  # tables still renders the page.
  defp recent_instances do
    Instance
    |> Ash.Query.for_read(:read)
    |> Ash.Query.sort(inserted_at: :desc)
    |> Ash.Query.limit(5)
    |> Ash.Query.load([:subject_label, :current_node])
    |> Ash.read!(authorize?: false)
  rescue
    _ -> []
  end
end
