defmodule ClinicDemo.Repo.Migrations.InitialSchedulingSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:appointments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scheduled_at, :utc_datetime, null: false
      add :duration_minutes, :bigint, null: false, default: 30
      add :reason, :text, null: false
      add :status, :text, null: false, default: "scheduled"
      add :notes, :text
      add :cancellation_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :patient_id, :uuid, null: false
      add :clinician_id, :uuid, null: false
    end

    create table(:clinicians, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:appointments) do
      modify :clinician_id,
             references(:clinicians,
               column: :id,
               name: "appointments_clinician_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:clinicians) do
      add :full_name, :text, null: false
      add :role, :text, null: false, default: "veterinarian"
      add :license_number, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:clinicians, [:license_number], name: "clinicians_unique_license_index")

    create table(:patients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:appointments) do
      modify :patient_id,
             references(:patients,
               column: :id,
               name: "appointments_patient_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:patients) do
      add :name, :text, null: false
      add :species, :text, null: false
      add :breed, :text
      add :date_of_birth, :date
      add :weight_kg, :decimal
      add :microchip_number, :text
      add :owner_email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:patients, [:microchip_number], name: "patients_unique_microchip_index")
  end

  def down do
    drop_if_exists unique_index(:patients, [:microchip_number],
                     name: "patients_unique_microchip_index"
                   )

    alter table(:patients) do
      remove :updated_at
      remove :inserted_at
      remove :owner_email
      remove :microchip_number
      remove :weight_kg
      remove :date_of_birth
      remove :breed
      remove :species
      remove :name
    end

    drop constraint(:appointments, "appointments_clinician_id_fkey")

    drop constraint(:appointments, "appointments_patient_id_fkey")

    alter table(:appointments) do
      modify :patient_id, :uuid
    end

    drop table(:patients)

    drop_if_exists unique_index(:clinicians, [:license_number],
                     name: "clinicians_unique_license_index"
                   )

    alter table(:clinicians) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :license_number
      remove :role
      remove :full_name
    end

    alter table(:appointments) do
      modify :clinician_id, :uuid
    end

    drop table(:clinicians)

    drop table(:appointments)
  end
end
