defmodule ClinicDemo.Repo.Migrations.AddDecisionsAndVisits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      add :severity, :bigint, null: false, default: 2
      add :triage_urgency, :text
      add :discharged_at, :utc_datetime
    end

    create table(:bpmn_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :version, :bigint, null: false
      add :status, :text, null: false, default: "draft"
      add :xml, :text, null: false
      add :graph, :map
      add :errors, {:array, :map}, default: []
      add :content_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:bpmn_definitions, [:key, :version],
             name: "bpmn_definitions_unique_key_version_index"
           )

    create index(:bpmn_definitions, [:key, :status], unique: true, where: "status = 'draft'")

    create table(:bpmn_human_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :node_id, :text, null: false
      add :name, :text, null: false
      add :status, :text, null: false, default: "open"
      add :assignee_type, :text
      add :assignee_id, :uuid
      add :claimed_at, :utc_datetime_usec
      add :due_at, :utc_datetime_usec
      add :outcome, :text
      add :decided_by_id, :uuid
      add :delegated_from_id, :uuid
      add :timer_job_ids, {:array, :bigint}, default: []
      add :comment, :text
      add :on_complete, :map, default: %{}
      add :subject_type, :text
      add :subject_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :instance_id, :uuid
      add :token_id, :uuid
    end

    create table(:bpmn_instances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:bpmn_human_tasks) do
      modify :instance_id,
             references(:bpmn_instances,
               column: :id,
               name: "bpmn_human_tasks_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bpmn_instances) do
      add :subject_type, :text, null: false
      add :subject_id, :uuid, null: false
      add :correlation_id, :text
      add :status, :text, null: false, default: "running"
      add :started_by_id, :uuid
      add :parent_instance_id, :uuid
      add :parent_token_id, :uuid
      add :trigger_depth, :bigint, null: false, default: 0
      add :outcome, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :definition_id,
          references(:bpmn_definitions,
            column: :id,
            name: "bpmn_instances_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:bpmn_process_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :instance_id,
          references(:bpmn_instances,
            column: :id,
            name: "bpmn_process_events_instance_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :token_id, :uuid
      add :node_id, :text
      add :task_id, :uuid
      add :kind, :text, null: false
      add :data, :map, default: %{}

      add :recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:bpmn_task_candidates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :principal_type, :text, null: false
      add :principal_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :task_id,
          references(:bpmn_human_tasks,
            column: :id,
            name: "bpmn_task_candidates_task_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:bpmn_task_candidates, [:task_id, :principal_type, :principal_id],
             name: "bpmn_task_candidates_unique_task_principal_index"
           )

    create table(:bpmn_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:bpmn_human_tasks) do
      modify :token_id,
             references(:bpmn_tokens,
               column: :id,
               name: "bpmn_human_tasks_token_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:bpmn_human_tasks, [:subject_type, :subject_id, :node_id],
             unique: true,
             where: "status IN ('open','claimed')"
           )

    alter table(:bpmn_tokens) do
      add :node_id, :text, null: false
      add :status, :text, null: false, default: "active"
      add :parent_token_id, :uuid
      add :fork_id, :uuid
      add :attempts, :bigint, default: 0
      add :routing, :map, default: %{}
      add :parked_at, :utc_datetime_usec
      add :correlation_key, :text
      add :subscription_signature, :text
      add :lookback_until, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :instance_id,
          references(:bpmn_instances,
            column: :id,
            name: "bpmn_tokens_instance_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:bpmn_tokens, [:subscription_signature, :instance_id],
             name: "bpmn_tokens_waiting_index",
             where: "status = 'waiting'"
           )

    create table(:dmn_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :version, :bigint, null: false
      add :status, :text, null: false, default: "draft"
      add :xml, :text, null: false
      add :graph, :map
      add :errors, {:array, :map}, default: []
      add :content_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:dmn_definitions, [:key, :version],
             name: "dmn_definitions_unique_key_version_index"
           )

    create index(:dmn_definitions, [:key, :status], unique: true, where: "status = 'draft'")

    create table(:dmn_evaluations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :definition_id,
          references(:dmn_definitions,
            column: :id,
            name: "dmn_evaluations_definition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :definition_key, :text, null: false
      add :definition_version, :bigint, null: false
      add :decision_id, :text, null: false
      add :inputs, :map, default: %{}
      add :outputs, :map, default: %{}
      add :matched_rule_ids, {:array, :text}, default: []
      add :hit_policy, :text
      add :duration_us, :bigint
      add :error, :map
      add :correlation_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:dmn_evaluations, [:definition_id])

    create index(:dmn_evaluations, [:correlation_id])
  end

  def down do
    drop_if_exists index(:dmn_evaluations, [:correlation_id])

    drop_if_exists index(:dmn_evaluations, [:definition_id])

    drop constraint(:dmn_evaluations, "dmn_evaluations_definition_id_fkey")

    drop table(:dmn_evaluations)

    drop_if_exists index(:dmn_definitions, [:key, :status])

    drop_if_exists unique_index(:dmn_definitions, [:key, :version],
                     name: "dmn_definitions_unique_key_version_index"
                   )

    drop table(:dmn_definitions)

    drop_if_exists index(:bpmn_tokens, [:subscription_signature, :instance_id],
                     name: "bpmn_tokens_waiting_index"
                   )

    drop constraint(:bpmn_tokens, "bpmn_tokens_instance_id_fkey")

    alter table(:bpmn_tokens) do
      remove :instance_id
      remove :updated_at
      remove :inserted_at
      remove :lookback_until
      remove :subscription_signature
      remove :correlation_key
      remove :parked_at
      remove :routing
      remove :attempts
      remove :fork_id
      remove :parent_token_id
      remove :status
      remove :node_id
    end

    drop_if_exists index(:bpmn_human_tasks, [:subject_type, :subject_id, :node_id])

    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_token_id_fkey")

    drop constraint(:bpmn_human_tasks, "bpmn_human_tasks_instance_id_fkey")

    alter table(:bpmn_human_tasks) do
      modify :token_id, :uuid
    end

    drop table(:bpmn_tokens)

    drop constraint(:bpmn_task_candidates, "bpmn_task_candidates_task_id_fkey")

    drop_if_exists unique_index(:bpmn_task_candidates, [:task_id, :principal_type, :principal_id],
                     name: "bpmn_task_candidates_unique_task_principal_index"
                   )

    drop table(:bpmn_task_candidates)

    drop constraint(:bpmn_process_events, "bpmn_process_events_instance_id_fkey")

    drop table(:bpmn_process_events)

    drop constraint(:bpmn_instances, "bpmn_instances_definition_id_fkey")

    alter table(:bpmn_instances) do
      remove :definition_id
      remove :updated_at
      remove :inserted_at
      remove :outcome
      remove :trigger_depth
      remove :parent_token_id
      remove :parent_instance_id
      remove :started_by_id
      remove :status
      remove :correlation_id
      remove :subject_id
      remove :subject_type
    end

    alter table(:bpmn_human_tasks) do
      modify :instance_id, :uuid
    end

    drop table(:bpmn_instances)

    drop table(:bpmn_human_tasks)

    drop_if_exists index(:bpmn_definitions, [:key, :status])

    drop_if_exists unique_index(:bpmn_definitions, [:key, :version],
                     name: "bpmn_definitions_unique_key_version_index"
                   )

    drop table(:bpmn_definitions)

    alter table(:appointments) do
      remove :discharged_at
      remove :triage_urgency
      remove :severity
    end
  end
end
