defmodule ClinicDemo.Decisions do
  @moduledoc """
  The clinic's business rules, held as DMN and evaluated rather than compiled in.

  One decision lives here: `appointment.triage`, which answers how urgently an
  animal needs to be seen. It is in `priv/decisions/appointment_triage.dmn`
  because a head vet changes a triage threshold on a business timescale, and the
  point of holding a rule this way is that changing it does not need a deploy.

  Two resources, both generated by `ash_decisions`:

    * `DecisionTable` — the DMN document, versioned, `draft → published → retired`.
    * `Evaluation` — append-only evidence of what each invoked decision saw and
      decided.

  The architectural line the package draws, and this domain keeps: **a decision
  decides; it never acts, never validates and never authorizes**. Nothing here
  writes to an appointment. `ClinicDemo.Scheduling.Appointment` does that, in an
  action, where every other caller goes through the same guard.
  """

  use Ash.Domain

  resources do
    resource ClinicDemo.Decisions.DecisionTable do
      define :create_decision, action: :create
      define :publish_decision, action: :publish
      define :latest_published_decision, action: :latest_published, args: [:key]
    end

    resource ClinicDemo.Decisions.Evaluation do
      define :list_evaluations, action: :read
    end
  end
end
