defmodule ClinicDemo.Visits do
  @moduledoc """
  The appointment lifecycle, as a process.

  A booked appointment gets an instance of the `appointment_visit` process, drawn
  in `priv/processes/appointment_visit.bpmn`. The process walks a visit from the
  phone call to the front door: it asks the triage decision how urgent this is,
  waits for the animal to arrive, waits for the vet, waits — if the vet asked for
  bloods — for the lab, and discharges.

  Six resources, all generated by `ash_bpmn`, plus the three callback modules a
  host has to supply:

    * `ClinicDemo.Visits.Roster` — who a human task is for. Resolved against the
      real `Clinician` table, not a hard-coded list.
    * `ClinicDemo.Visits.Invoker` — what a service task does. Every one of them
      is an ordinary `ClinicDemo.Scheduling` code interface call.
    * `ClinicDemo.Decisions.Resolver` — what a business rule task decides.

  The architectural line: **the graph orchestrates; it never decides, validates
  or authorizes.** `:discharge` refuses an appointment that has not been written
  up, and it refuses the process exactly as it refuses anybody else.
  """

  use Ash.Domain

  resources do
    resource ClinicDemo.Visits.Definition do
      define :create_process, action: :create
      define :publish_process, action: :publish
      define :latest_published_process, action: :latest_published, args: [:key]
    end

    resource ClinicDemo.Visits.Instance do
      define :list_instances, action: :read
    end

    resource ClinicDemo.Visits.Token do
      define :list_tokens, action: :read
    end

    resource ClinicDemo.Visits.HumanTask do
      define :list_human_tasks, action: :read
    end

    resource ClinicDemo.Visits.TaskCandidate

    resource ClinicDemo.Visits.ProcessEvent do
      define :list_process_events, action: :read
    end
  end
end
